# Generated by Django 3.0.3 on 2020-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='post',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
