# Generated by Django 3.0.3 on 2020-02-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200216_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='end_work_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
